[project]
name = "spotify"
version = "0.1.0"
description = "Uses the Spotify API to load my listen data"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.6",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
